all:
  # Variables applied to every host
   vars:
    ansible_host: localhost
    ansible_user: node
    ansible_password: node1234
    become_ansible_user: node
    become_ansible_password: node1234
    ansible_connection: ssh

# Metagroup called myhosts
myhosts:
  hosts:
    # Aliases
    ubuntu-ssh-1:
      ansible_port: 2222
    ubuntu-ssh-2:
      ansible_port: 2223

other:
  hosts:
    ubuntu-ssh-3:
      ansible_port: 2224
