global:
  # Data collection period
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ansible-vms'
    scrape_interval: 5s
    scheme: http
    static_configs:
      - targets: ['ansible-vm-01:22', 'ansible-vm-02:22', 'ansible-vm-03:22']

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
